### ISSUE TITLE
[1.12.2] [3.0] Crash when crafting terrestrial focus

### ISSUE THREAD

**Issue by wamc2017** [ejektaflex/NaturalPledge#1]
Hi,

the game crashes when the terrestrial focus is crafted. Strangely it produces two logs (one server and one client, I tested it in singleplayer):
https://gist.github.com/wamc2017/4fdbac378b73d81701da6689dedc4180
https://gist.github.com/wamc2017/62209a7a37c70e8b881e858af6e652ad

Mods used to test this issue (no other mods installed):
Baubles-1.12-1.5.2
Botania r1.10-356
Forgelin-1.7.4
jei_1.12.2-4.12.0.216
librarianlib-1.12.2-4.15
NaturalPledge-r3.0
forge-1.12.2-14.23.4.2760

Thanks for looking into it.

Best regards,
wamc

**Comment by ejektaflex** [comment]
v3.0.1 should have this fix.
