### ISSUE TITLE
[1.12.2] [3.0.1] Advancements aren't working/No way to obtain forbidden knowledge

### ISSUE THREAD

**Issue by wamc2017** [ejektaflex/NaturalPledge#5]
Hi,

I got the following errors in the log if I start up a world:

https://gist.github.com/wamc2017/176a46f35126ba76ec763cab3ea9af56

From my knowledge (played the mod the last time on 1.10.2) and from following code, those are needed to obtain the Forbidden Knowledge in the Lexica Botania:

https://github.com/ejektaflex/NaturalPledge/blob/b3ca3f081d829600905b75402f5a236b453432a0/src/main/java/com/wiresegal/naturalpledge/common/lexicon/LexiconEntries.kt#L126-L138

Thanks for looking into it.

Best regards,
wamc

**Comment by ejektaflex** [comment]
I can replicate this. Will be in the next hotfix release.

**Comment by ejektaflex** [comment]
Advancements should show up in 3.0.2 (all besides the last two, which need custom triggers. They will be re-implemented later.)
